apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello
  labels:
    name: hello
spec:
  rules:
  - host: {{ .Values.ingress.host | default "hello.tooling.k8s.aveniq.cloud" }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello
            port: 
              number: 80
