name: Build and Release CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            sspreitzer/hello-cicd-world:latest
            sspreitzer/hello-cicd-world:${{ steps.getversion.outputs.version }}
    outputs:
      version: ${{ steps.getversion.outputs.version }}

  
  Abnahme:
    runs-on: ubuntu-latest
    needs: Build
    container:
      image: sspreitzer/hello-cicd-world:${{ needs.Build.outputs.version }}
    steps:
      - name: Check if version file is correct
        run: test "$(cat /usr/src/app/VERSION)" = "${{ needs.Build.outputs.version }}"
      - name: Check if version served is correct
        run: curl http://localhost | grep ${{ needs.Build.outputs.version }}


  Release:
    runs-on: ubuntu-latest
    needs: Abnahme
    steps:
      - run: "true"
