name: Build and Release CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            sspreitzer/hello-cicd-world:latest
            sspreitzer/hello-cicd-world:${{ steps.getversion.outputs.version }}
  
  Abnahme:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Do nothing yet
        run: "true"

  Release:
    runs-on: ubuntu-latest
    needs: Abnahme
    steps:
      - name: Do nothing yet
        run: "true"
