name: Build and Release CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: latest
    